version: '3'
services:
  web:
    container_name: php-conf-chat-web
    image: php:8.2-fpm-alpine
    working_dir: '/app'
    ports:
      - 80:80
    command: php -S 0.0.0.0:80 -t public
    volumes:
      - '.:/app:z'
volumes:
  rabbitmq_data: